[package]
name = "kns-indexer"
version = "0.2.0"
edition = "2021"

[features]
simulation-mode = []

[dependencies]
anyhow = "1.0"
alloy-primitives = "0.8.15"
alloy-sol-types = "0.8.15"
hex = "0.4.3"
hyperware_process_lib = "1.0.2"
process_macros = "0.1"
rmp-serde = "1.1.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
wit-bindgen = "0.36.0"

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "hyperware:process"
