[package]
name = "help"
version = "0.1.0"
edition = "2021"

[features]
simulation-mode = []

[dependencies]
hyperware_process_lib = "1.0.3"
wit-bindgen = "0.36.0"

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "hyperware:process"
