name: rust tagged release in main CI

on:
  push:
    tags: ['v[0-9].[0-9]+.[0-9]+']

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: build and deploy hypedriver
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_PROD_API_HOST }}
        username: ${{ secrets.SSH_PROD_USER }}
        key: ${{ secrets.SSH_PROD_API_ED25519KEY }}
        port: ${{ secrets.SSH_PROD_PORT }}
        command_timeout: 60m
        script: |
          curl -X PUT http://localhost:8000/monitor/build-hyperdrive
