name: rust release-candidate CI

on:
  push:
    branches: [ release-candidate ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: build and deploy hyperdrive
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_API_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_API_ED25519KEY }}
        port: ${{ secrets.SSH_PORT }}
        command_timeout: 60m
        script: |
          curl -X PUT http://localhost:8000/monitor/build-hyperdrive
